### PR TITLE
Fix: Add route  to count all minted domains

### LINKED ISSUE #131: Create a new route `/stats/count_minted_domains`
## Description 📹

**Create a new route `/stats/count_minted_domains` similar to `src/endpoints/stats/count_domains.rs`, but that counts all domains ever created, including expired ones.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:

   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   - Add a new route `/stats/count_minted_domains`.
   - Create a new handler function `handler` in `src/endpoints/stats/count_minted_domains.rs`:
     - Remove the `expiry` filter in the MongoDB query so all domains are counted.
     - Keep the other filters as necessary.
     - Use the existing `AppState` and `CountDomainsQuery` structs.
   - Example implementation:

     ```rust
     #[route(get, "/stats/count_minted_domains", crate::endpoints::stats::count_minted_domains)]
     pub async fn handler(
         State(state): State<Arc<AppState>>,
         Query(query): Query<CountDomainsQuery>,
     ) -> impl IntoResponse {
         let mut headers = HeaderMap::new();
         headers.insert("Cache-Control", HeaderValue::from_static("max-age=60"));

         let domain_collection = state
             .starknetid_db
             .collection::<mongodb::bson::Document>("domains");
         let filter = doc! {
             "creation_date": { "$gte": query.since },
             "$or": [
                 { "_cursor.to": { "$exists": false } },
                 { "_cursor.to": Bson::Null },
             ],
         };

         let total = domain_collection.count_documents(filter, None).await;

         match total {
             Ok(count) => {
                 let response_data = CountDomainsData { count };
                 (StatusCode::OK, headers, Json(response_data)).into_response()
             }
             Err(e) => get_error(format!("Error while fetching from database: {:?}", e)),
         }
     }
     ```

   - Update `lib.rs` to include the new route.

3. **Run Tests and Commit Changes**:  
   - Write tests to verify that the new endpoint `/stats/count_minted_domains` works as expected.
   - Run all existing tests to ensure no regressions.
   - Commit the changes:

     ```bash
     git commit -m "Fix: Add route `/stats/count_minted_domains` to count all minted domains"
     ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by Bosun-Josh121**
close #131

### CODE REVIEW

File: src/endpoints/stats/count_minted_domains.rs [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+    match total {
+        Ok(count) => {
+            let response_data = CountMintedDomainsData { count };
+            (StatusCode::OK, headers, Json(response_data)).into_response()
+        }
+        Err(e) => get_error(format!("Error while fetching from database: {:?}", e)),
+    }
+}
+
+#[cfg(test)]
```
Comment (Marchand-Nicolas) [inline src/endpoints/stats/count_minted_domains.rs]: Please remove the test,  they don't compile

File: src/endpoints/stats/count_minted_domains.rs [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+use std::sync::Arc;
+
+#[derive(Serialize)]
+pub struct CountMintedDomainsData {
+    count: u64,
+}
+
+#[derive(Deserialize)]
+pub struct CountDomainsQuery {
+    since: i64,
```
Comment (Marchand-Nicolas) [inline src/endpoints/stats/count_minted_domains.rs]: Don't add a since parameter, as said in the issue, it should count all domains ever minted

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
A few changes and we're good

File: src/endpoints/stats/count_minted_domains.rs [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+    State(state): State<Arc<AppState>>,
+) -> impl IntoResponse {
+    let mut headers = HeaderMap::new();
+    headers.insert("Cache-Control", HeaderValue::from_static("max-age=60"));
+
+    let domain_collection = state
+        .starknetid_db
+        .collection::<mongodb::bson::Document>("domains");
+    let filter = doc! {
+        "creation_date": { "$gte": query.since },
```
Comment (Marchand-Nicolas) [inline src/endpoints/stats/count_minted_domains.rs]: You didn't update the code so it doesn't compile...
Test your code!
`cargo run`
```rs
error[E0425]: cannot find value `query` in this scope
src/endpoints/stats/count_minted_domains.rs:29:36
   |
29 |         "creation_date": { "$gte": query.since },
   |                                    ^^^^^ help: a tuple struct with a similar name exists: `Query`
   ```

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Doesn't compile

File: src/endpoints/stats/count_minted_domains.rs [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+pub async fn handler(
+    State(state): State<Arc<AppState>>,
+) -> impl IntoResponse {
+    let mut headers = HeaderMap::new();
+    headers.insert("Cache-Control", HeaderValue::from_static("max-age=60"));
+
+    let domain_collection = state
+        .starknetid_db
+        .collection::<mongodb::bson::Document>("domains");
+    let filter = doc! {
```
Comment (Marchand-Nicolas) [inline src/endpoints/stats/count_minted_domains.rs:28]: Add a check to verify the "domain" field is defined and we're good, well done!

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Almost!

**Review by Marchand-Nicolas — APPROVED** [review]
Perfect, well done, lgtm!
