### PR TITLE
Fix: Resolved warnings during cargo build

### LINKED ISSUE #103: Fix warnings
## Description 📹

**Fix the warnings when using `cargo build`, such as “use of deprecated method” warnings.**  
Several warnings are being raised during the build process when using `cargo build`. These warnings may include the use of deprecated methods or features. This issue aims to resolve these warnings to ensure a clean build process.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	- [ ] Identify all warnings generated by `cargo build`.
	- [ ] Locate the source of each warning in the codebase.
	- [ ] Update the code to use recommended or non-deprecated alternatives.
	- [ ] If you think some warnings can be ignored, such as the async_warning function that is currently unused, but that we'll probably use in the future, you can leave them.

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
   ```bash
   git commit -m "Fix: Resolved warnings during cargo build"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by pheobeayo**
closes #103

### CODE REVIEW

File: src/endpoints/referral/click_count.rs [hunk 1]
```diff
@@ -38,14 +38,14 @@ pub async fn handler(
     let mut output = Data { counts: vec![] };
     let mut i = 0;
     loop {
-        let start_naive_dt =
-            NaiveDateTime::from_timestamp_opt(query.since_day + i * query.spacing, 0).unwrap();
-        let start_time = Utc.from_utc_datetime(&start_naive_dt);
+        let _start_date_time =
```
Comment (Marchand-Nicolas) [inline src/endpoints/referral/click_count.rs]: Don't add a "_" at the start of the function name

File: src/endpoints/referral/click_count.rs [hunk 2]
```diff
@@ -38,14 +38,14 @@ pub async fn handler(
...
+            DateTime::from_timestamp(query.since_day + i * query.spacing, 0).unwrap();
+        let start_time = Utc::now();
```
Comment (Marchand-Nicolas) [inline src/endpoints/referral/click_count.rs]: Please reuse the original logic or something similar (Utc.from_utc_datetime(&start_naive_dt)), because this is not the same

File: src/endpoints/referral/click_count.rs [hunk 3]
```diff
@@ -38,14 +38,14 @@ pub async fn handler(
...
 
-        let end_naive_dt =
-            NaiveDateTime::from_timestamp_opt(query.since_day + (i + 1) * query.spacing, 0)
+        let _end_date_time =
+            DateTime::from_timestamp(query.since_day + (i + 1) * query.spacing, 0)
                 .unwrap();
-        let end_time = Utc.from_utc_datetime(&end_naive_dt);
+        let end_time = Utc::now();
```
Comment (Marchand-Nicolas) [inline src/endpoints/referral/click_count.rs]: Here too

File: src/endpoints/referral/revenue.rs [hunk 4]
```diff
@@ -38,14 +38,14 @@ pub async fn handler(
     let mut output = Data { revenues: vec![] };
     let mut i = 0;
     loop {
-        let start_naive_dt =
-            NaiveDateTime::from_timestamp_opt(query.since_date + i * query.spacing, 0).unwrap();
-        let start_time = Utc.from_utc_datetime(&start_naive_dt);
+        let _start_date_time  =
```
Comment (Marchand-Nicolas) [inline src/endpoints/referral/revenue.rs]: Same

File: src/endpoints/referral/sales_count.rs [hunk 5]
```diff
@@ -38,14 +38,14 @@ pub async fn handler(
     let mut output = Data { counts: vec![] };
     let mut i = 0;
     loop {
-        let start_naive_dt =
-            NaiveDateTime::from_timestamp_opt(query.since_date + i * query.spacing, 0).unwrap();
-        let start_time = Utc.from_utc_datetime(&start_naive_dt);
+        let _start_date_time =
```
Comment (Marchand-Nicolas) [inline src/endpoints/referral/sales_count.rs]: Same

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

File: src/endpoints/referral/revenue.rs (hunk 4 above)
Comment (pheobeayo) [reply src/endpoints/referral/revenue.rs]: okay

File: src/endpoints/referral/click_count.rs (hunk 1 above)
Comment (pheobeayo) [reply src/endpoints/referral/click_count.rs]: okay

File: src/endpoints/referral/click_count.rs (hunk 3 above)
Comment (pheobeayo) [reply src/endpoints/referral/click_count.rs]: okay

File: src/endpoints/referral/click_count.rs (hunk 2 above)
Comment (pheobeayo) [reply src/endpoints/referral/click_count.rs]: okay

File: src/endpoints/referral/sales_count.rs [hunk 6]
```diff
@@ -26,30 +26,31 @@ pub struct IdQuery {
...
     let mut i = 0;
     loop {
-        let start_naive_dt =
-            NaiveDateTime::from_timestamp_opt(query.since_date + i * query.spacing, 0).unwrap();
-        let start_time = Utc.from_utc_datetime(&start_naive_dt);
+        let start_date_time = DateTime::from_timestamp(
+            query.since_date + i * query.spacing,
+            0
+        ).unwrap();
+        let start_time = start_date_time;
```
Comment (Marchand-Nicolas) [inline src/endpoints/referral/sales_count.rs]: This variable is not useful. You can remove it and rename start_date_time. It also applies to end_time

File: src/endpoints/referral/revenue.rs [hunk 7]
```diff
@@ -26,30 +26,31 @@ pub struct IdQuery {
...
     let mut i = 0;
     loop {
-        let start_naive_dt =
-            NaiveDateTime::from_timestamp_opt(query.since_date + i * query.spacing, 0).unwrap();
-        let start_time = Utc.from_utc_datetime(&start_naive_dt);
+        let start_date_time = DateTime::from_timestamp(
+            query.since_date + i * query.spacing,
+            0
+        ).unwrap();
+        let start_time = start_date_time;
```
Comment (Marchand-Nicolas) [inline src/endpoints/referral/revenue.rs]: Same

File: src/endpoints/referral/click_count.rs [hunk 8]
```diff
@@ -26,40 +26,39 @@ pub struct IdQuery {
...
     let mut i = 0;
     loop {
-        let start_naive_dt =
-            NaiveDateTime::from_timestamp_opt(query.since_day + i * query.spacing, 0).unwrap();
-        let start_time = Utc.from_utc_datetime(&start_naive_dt);
+        let start_date_time = DateTime::from_timestamp(
+            query.since_day + i * query.spacing,
+            0
+        ).unwrap();
+        let start_time = start_date_time;
```
Comment (Marchand-Nicolas) [inline src/endpoints/referral/click_count.rs]: Same

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Some variables that have no meanings

**Review by Marchand-Nicolas — APPROVED** [review]
Perfect! Lgtm!
